settings:
  # COM Port without spaces [COM3]    
  defaultCOMPort: COM3
  # Baud rates [4800, 9600, 19200, 38400, 57600, 115200]
  defaultBaudRate: 9600
  # Window State [minimized, normal]
  windowState: minimized
  # Automatically Start with Windows [true, false]
  winStart: remove
  # Character to add to the start of the input [any string]
  startChar: "*"
  # Character to add to the end of the input [tab, enter, none]
  endChar: enter
